from __future__ import annotations

from typing import Any, Protocol


class PracticeManagementProvider(Protocol):
    """Shared surface for Clio (v1) and a future MyCase adapter."""

    name: str

    async def close(self) -> None: ...

    async def health(self) -> dict[str, Any]: ...

    async def who_am_i(self) -> dict[str, Any]: ...

    async def find_contacts(self, **kwargs: Any) -> dict[str, Any]: ...

    async def get_contact(self, **kwargs: Any) -> dict[str, Any]: ...

    async def create_person(self, **kwargs: Any) -> dict[str, Any]: ...

    async def create_company(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update_contact(self, **kwargs: Any) -> dict[str, Any]: ...

    async def find_matters(self, **kwargs: Any) -> dict[str, Any]: ...

    async def get_matter(self, **kwargs: Any) -> dict[str, Any]: ...

    async def create_matter(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update_matter(self, **kwargs: Any) -> dict[str, Any]: ...

    async def list_calendar_entries(self, **kwargs: Any) -> dict[str, Any]: ...

    async def create_calendar_entry(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update_calendar_entry(self, **kwargs: Any) -> dict[str, Any]: ...

    async def list_tasks(self, **kwargs: Any) -> dict[str, Any]: ...

    async def create_task(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update_task(self, **kwargs: Any) -> dict[str, Any]: ...

    async def list_activities(self, **kwargs: Any) -> dict[str, Any]: ...

    async def create_time_entry(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update_time_entry(self, **kwargs: Any) -> dict[str, Any]: ...

    async def list_notes(self, **kwargs: Any) -> dict[str, Any]: ...

    async def create_note(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update_note(self, **kwargs: Any) -> dict[str, Any]: ...

    async def list_documents(self, **kwargs: Any) -> dict[str, Any]: ...

    async def raw_request(self, **kwargs: Any) -> dict[str, Any]: ...
